builders:
  ota_generators:
    target: ":ota_generators"
    import: "package:ota_generator/ota_generator.dart"
    builder_factories: ["generateAppLocalize"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
